sudo: false
language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
install:
- pip install tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist
  server: https://test.pypi.org/legacy/
  user: __token__ 
  password:
    secure: DJUp7K7eL1EfeYwigb/G0/Dxr1du+eYz9JF7x01A5BYfrPn6xV6CQMa6hKG/tZ5MYE/jHgbkQ/r3KMJ26p9FttHhEzsR0oYi3e05lcSy/4bAc87VvrIpiF5J8a0hlRUxsad9oal4WmBAkJS3d5yE/hW2eHPWEAJJgaVKGswmeTxUywwdv6Bui12gpFJINqRXadnuQBmwvnQevNzaISPdNtudr9qUbb+161O4jQH/BnZa+yaCkZx7K5gICu92Xx4V5aYbv+5VNledX2mBc5b/RH/fnNPP3WwUag+D9Mle5a6s+MqEdgEhhYgFVRNNEjhciE7stZeV99hulzcYo/QZ3kOz7QThqpE0uRd8JEuX5+lFE+B6qoS1Awh+XO6fg9gVbzawvy4XxF8cFRBBMXMIXa2nHjAJJxvS0hNTBTkauiei2bcS7SX/iNfHbm9EU9mcrDjzClCC52mh9em224E0gA9ZX29//NgdB1EfA+n+jVAhGjgPdYUeVQNkCeDsaXUaPEacs02QlNSXemAL4G4XT/wxHdVdFG3biMfs6N0SM+UpzRjr9ZEYnt6DHiOu0en/ibhv4J8to9xO6xXryNG0dy/6lwRT5nxkmOOhl+TwlJxemOdOkyTI1ltbYq0eB9nW7AUWjjKcv6diOxQk9W7f5ZKyEjUvwnfZEyyfJ3Ymk5Y=
  on:
    branch: master
    tags: false
    python: 3.6
  skip_cleanup: true
