sudo: false
language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
install:
- pip install tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist
  server: https://test.pypi.org/legacy/
  user: __token__
  password:
    secure: wwCr+Ajzy2WflJylWR8iC6z0PADWj9ZmC544RXc+3RMR9ZTyiWx2N1G03Tmf3DKwxjFQLe4mT5dPjQ7tN4kmqQUBrq0BM9VyvI7LxwSHIAAH5tYh0stt9NviJ+lflcm+kQQWVJFe/2pg8mCNippf/BvVF9pd2/ZlxoxM2nmI0O5GbSKr0YmbCDftEmcv4wwdOHHjvozGJFQ0/S5tyC8IZcbu3uzHZrUSvicqLul3kP/pB8YBBtXwG2/GMnxnbM2lzBc9woBP5+K1G7PNL1eO+lGDGrtKauPi/7VE8xrEZg+P/ddaHbkuQwVX54vbusgy8gsf3Hehm6LixBy5KnkFLYmKMCwMhg5bBOY5WtOvpNYey8UOpQJjHgS1ozy7kHQ+4gsu3zc89Q1VQo8IS56t32B9FZpHDNNIAqp36kwZyVufdK8RdKy/iVTuJ/Y34bXxA48CJLHHVr4YBmM4Purb4TSqTGRoDtdsEgTPYDMXfO5mj80u6vFqD4uRYnCNrMwqdEL7TyKMIIf3qnz4p/VzSS9Pe/I5n/nSJ084PT7xQQgvVfIzWdVQRNUwxm/OiMoqFf9K+sClMZhItGGCm5LbcUu1CJYBo+u8p9jDNESf36GQ/p6fYi2Gj5jgKqSQvQMWsPl9A+BrBqgrVqBGMy7L7TvkgqcWDNMPaZXbIRRs7UI=
  on:
    branch: master
    tags: false
    python: 3.6
  skip_cleanup: true
